language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t qasim/myreactbuild -f Dockerfile.dev .

script:
  - echo Hello
  - docker run -e CI=true qasim/myreactbuild npm run test